force-app/main/default/objects/Man_hour__c/Man_hour__c.object-meta.xml
<CustomObject>
    <label>Man hour</label>
    <nameField>
        <displayFormat>MH{YY}{MM}-{00000}</displayFormat>
        <label>Man hour No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Man hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Man_hour__c/fields/Performed_Date__c.field-meta.xml
<CustomField>
    <fullName>Performed_Date__c</fullName>
    <label>Performed Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Man_hour__c/fields/Performed_Hours__c.field-meta.xml
<CustomField>
    <fullName>Performed_Hours__c</fullName>
    <defaultValue>00.00</defaultValue>
    <label>Performed Hours</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Man_hour__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <formula>ProjectAssign_No__r.Project_No__r.Project_Name__c</formula>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Man_hour__c/fields/Project_No__c.field-meta.xml
<CustomField>
    <fullName>Project_No__c</fullName>
    <formula>ProjectAssign_No__r.Project_No__r.Name</formula>
    <label>Project No.</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Man_hour__c/fields/ProjectAssign_Name__c.field-meta.xml
<CustomField>
    <fullName>ProjectAssign_Name__c</fullName>
    <formula>ProjectAssign_No__r.Project_No__c</formula>
    <label>ProjectAssign Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Man_hour__c/fields/ProjectAssign_No__c.field-meta.xml
<CustomField>
    <fullName>ProjectAssign_No__c</fullName>
    <label>ProjectAssign No.</label>
    <referenceTo>ProjectAssign__c</referenceTo>
    <relationshipLabel>Man hours</relationshipLabel>
    <relationshipName>Man_hours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Man_hour__c/fields/Remark__c.field-meta.xml
<CustomField>
    <fullName>Remark__c</fullName>
    <label>Remark</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Man_hour__c/fields/Work__c.field-meta.xml
<CustomField>
    <fullName>Work__c</fullName>
    <label>Work</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ManHoursInputController.cls
public with sharing class ManHoursInputController {

    @AuraEnabled(cacheable=false)
    public static List<ProjectAssign__c> getProjectList(String userId, String year, String month){
        try {
            Id user = (Id)userId;
            Date tempDate = Date.valueOf(year+'-'+month+'-15');
            Integer numberOfDays = Date.daysInMonth(tempDate.year(), tempDate.month());

            Date startDateTemp = Date.newInstance(tempDate.year(), tempDate.month(), 1);
            Date endDateTemp = Date.newInstance(tempDate.year(), tempDate.month(), numberOfDays);

            List<ProjectAssign__c> projectAssignList = [SELECT
                                                            Id,
                                                            Name,
                                                            Project_No__r.Project_Name__c,
                                                            Start_Date__c,
                                                            Due_Date__c,
                                                            Actual_Hours__c,
                                                            Planning_Hours__c,
                                                            (SELECT Id,
                                                                    Name,
                                                                    Work__c,
                                                                    Performed_Date__c,
                                                                    Performed_Hours__c,
                                                                    Remark__c
                                                                FROM Man_hours__r
                                                                WHERE Performed_Date__c >= :startDateTemp AND Performed_Date__c <= :endDateTemp
                                                                ORDER BY Performed_Date__c ASC)
                                                        FROM ProjectAssign__c
                                                        WHERE Assignee__c =:user
                                                            AND (
                                                                (Start_Date__c >= :startDateTemp AND Start_Date__c <= :endDateTemp)
                                                                OR (Due_Date__c >= :startDateTemp AND Due_Date__c <= :endDateTemp)
                                                            )
                                                        ];
            return projectAssignList;
        } catch (Exception e) {
            System.debug(e.getMessage());
            return new List<ProjectAssign__c>();
        }
    }

    @AuraEnabled(cacheable=false)
    public static ProjectAssign__c getManhourList(String projectAssignId, String dateSelected){
        try {
            Id projectAssignIdTemp = (Id)projectAssignId;
            Date tempDate = Date.valueOf(dateSelected);
            ProjectAssign__c projectAssign = [SELECT
                                                Id,
                                                Name,
                                                Project_No__r.Project_Name__c,
                                                Start_Date__c,
                                                Due_Date__c,
                                                (SELECT
                                                    Id,
                                                    Name,
                                                    Performed_Date__c,
                                                    Performed_Hours__c,
                                                    Project_Name__c,
                                                    Project_No__c,
                                                    ProjectAssign_Name__c,
                                                    ProjectAssign_No__c,
                                                    Remark__c,
                                                    Work__c
                                                FROM Man_hours__r
                                                WHERE Performed_Date__c =:tempDate
                                                ORDER BY CreatedDate ASC)
                                            FROM ProjectAssign__c
                                            WHERE Id =:projectAssignIdTemp
                                            LIMIT 1];
            return projectAssign;
        } catch (Exception e) {
            System.debug(e.getMessage());
            return new ProjectAssign__c();
        }
    }

    @AuraEnabled(cacheable=false)
    public static List<Man_hour__c> addManhour(String projectAssignId, String performedDate){
        Date performedDateTemp = Date.valueOf(performedDate);
        try {
            Man_hour__c manHour = new Man_hour__c(
                                        Work__c='',
                                        ProjectAssign_No__c=projectAssignId,
                                        Performed_Date__c=performedDateTemp,
                                        Performed_Hours__c=0,
                                        Remark__c=''
                                    );
            insert manHour;
            List<Man_hour__c> manHours = [SELECT Id,
                                            Name,
                                            Work__c,
                                            Performed_Date__c,
                                            Performed_Hours__c,
                                            ProjectAssign_No__c,
                                            Remark__c
                                        FROM Man_hour__c
                                        WHERE  ProjectAssign_No__c=:projectAssignId AND Performed_Date__c=:performedDateTemp
                                        ORDER BY CreatedDate ASC];
            return manHours;
        } catch (Exception e) {
            System.debug(e.getMessage());
            throw new AuraHandledException('Failed to insert man-hour: ' + e.getMessage());
        }
    }

    @AuraEnabled(cacheable=false)
    public static List<Man_hour__c> editManhour(List<Man_hour__c> editRecords){
        try {
            List<Man_hour__c> manHours = new List<Man_hour__c>();
            if(editRecords.size()>0) {
                update editRecords;
                Man_hour__c manHour = [SELECT Id, Performed_Date__c, ProjectAssign_No__c FROM Man_hour__c WHERE Id=:editRecords.get(0).Id LIMIT 1];
                manHours = [SELECT Id,
                                Name,
                                Work__c,
                                Performed_Date__c,
                                Performed_Hours__c,
                                ProjectAssign_No__c,
                                Remark__c
                            FROM Man_hour__c
                            WHERE ProjectAssign_No__c=:manHour.ProjectAssign_No__c AND Performed_Date__c=:manHour.Performed_Date__c
                            ORDER BY CreatedDate ASC];
            }
            return manHours;
        } catch (Exception e) {
            System.debug(e.getMessage());
            throw new AuraHandledException('Failed to edit man-hour: ' + e.getMessage());
        }
    }

    @AuraEnabled(cacheable=false)
    public static List<Man_hour__c> deleteManhour(List<Man_hour__c> deleteRecords){
        try {
            Id projectAssignId = null;
            Date performedDate = null;
            List<Man_hour__c> manHours = new List<Man_hour__c>();

            if(deleteRecords.size()>0) {
                Man_hour__c manHour = [SELECT Id, Performed_Date__c, ProjectAssign_No__c FROM Man_hour__c WHERE Id=:deleteRecords.get(0).Id LIMIT 1];
                delete deleteRecords;
                manHours = [SELECT Id,
                                Name,
                                Work__c,
                                Performed_Date__c,
                                Performed_Hours__c,
                                ProjectAssign_No__c,
                                Remark__c
                            FROM Man_hour__c
                            WHERE ProjectAssign_No__c=:manHour.ProjectAssign_No__c AND Performed_Date__c=:manHour.Performed_Date__c
                            ORDER BY CreatedDate ASC];
            }
            return manHours;
        } catch (Exception e) {
            System.debug(e.getMessage());
            throw new AuraHandledException('Failed to delete man-hour: ' + e.getMessage());
        }
    }

    @AuraEnabled(cacheable=false)
    public static User getUserAvatar(String Id) {
        try {
            User user = [SELECT Id, Name, Title, Department, Manager.Name, Manager.Id, MediumPhotoUrl FROM User WHERE Id = :Id LIMIT 1];
            return user;
        } catch (Exception e) {
            System.debug(e);
            return null;
        }
    }
}