force-app/main/default/objects/ApplicationItem__c/ApplicationItem__c.object-meta.xml
<CustomObject>
    <label>ApplicationItem</label>
    <nameField>
        <label>ApplicationItem No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApplicationItems</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationItem__c/fields/Period_Leave__c.field-meta.xml
<CustomField>
    <fullName>Period_Leave__c</fullName>
    <label>Period Leave</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All day</fullName>
            </value>
            <value>
                <fullName>AM leave</fullName>
            </value>
            <value>
                <fullName>PM leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApplicationItem__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sick leave</fullName>
            </value>
            <value>
                <fullName>Annual leave</fullName>
            </value>
            <value>
                <fullName>Personal leave</fullName>
            </value>
            <value>
                <fullName>Refresh Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement leave</fullName>
            </value>
            <value>
                <fullName>Marriage leave</fullName>
            </value>
            <value>
                <fullName>Maternity leave</fullName>
            </value>
            <value>
                <fullName>Military service leave</fullName>
            </value>
            <value>
                <fullName>Ordination leave</fullName>
            </value>
            <value>
                <fullName>Sterilization leave</fullName>
            </value>
            <value>
                <fullName>Training or knowledge leave</fullName>
            </value>
            <value>
                <fullName>Unpaid leave</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApplicationItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApplicationItem__c/fields/Term_From__c.field-meta.xml
<CustomField>
    <fullName>Term_From__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ApplicationItemTriggerLogic.cls
public class ApplicationItemTriggerLogic {

    public void setLeaveDateTime(List<ApplicationItem__c> newList){
        for(ApplicationItem__c appl : newList){
            if(appl.Status__c == 'Approved'){
                // start date and time 
                Datetime strDateTime =  ( 'PM leave'==appl.Period_Leave__c 
                                        ? DateTime.newInstance(appl.Term_From__c.year(), appl.Term_From__c.month(),appl.Term_From__c.day() , 13, 0, 0)
                                        : DateTime.newInstance(appl.Term_From__c.year(), appl.Term_From__c.month(),appl.Term_From__c.day() , 8, 30, 0)
                                    );
                // end date and time 
                Datetime endDateTime =  ( 'AM leave'==appl.Period_Leave__c 
                                        ? DateTime.newInstance(appl.Term_From__c.year(), appl.Term_From__c.month(),appl.Term_From__c.day() , 12, 0, 0)
                                        : DateTime.newInstance(appl.Term_From__c.year(), appl.Term_From__c.month(),appl.Term_From__c.day() , 17, 0, 0)
                                    );                
                // set even for block calendar
                Event event = new Event();
                event.WhatId = appl.ID;
                event.Subject = appl.Request_Type__c;
                event.OwnerId = appl.OwnerId;
                event.StartDateTime = strDateTime;
                event.EndDateTime = endDateTime;
                event.Description = appl.Period_Leave__c;
                
                insert event;
            }
        }
    }
    
}