force-app/main/default/objects/ApplicationItem__c/ApplicationItem__c.object-meta.xml
<CustomObject>
    <label>ApplicationItem</label>
    <nameField>
        <label>ApplicationItem No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApplicationItems</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EventTriggerLogic.cls
public class EventTriggerLogic {

    // check applicationItem record when status is apporved
    public void checkApplicationItemPreventEditCalendar(List<Event> eventList, String acction){
        Event event = eventList[0];
        if(event.WhatId!=null 
				&& Schema.ApplicationItem__c.SObjectType==event.WhatId.getSobjectType()){            
            List<ApplicationItem__c> applicationItems = [SELECT Id, Status__c FROM ApplicationItem__c WHERE Id =: event.WhatId LIMIT 1];
            if(!applicationItems.isEmpty()){
                if( applicationItems[0]!=null && applicationItems[0].Status__c == 'Approved' && event.CreatedById != UserInfo.getUserId() ){
                    // add error massage 
                    event.addError('Cannot '+acction+', Please contact your manager.');
                }
            }
        }
    }
}