force-app/main/default/objects/ApplicationItem__c/ApplicationItem__c.object-meta.xml
<CustomObject>
    <label>ApplicationItem</label>
    <nameField>
        <label>ApplicationItem No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApplicationItems</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationItem__c/fields/Period_Leave__c.field-meta.xml
<CustomField>
    <fullName>Period_Leave__c</fullName>
    <label>Period Leave</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All day</fullName>
            </value>
            <value>
                <fullName>AM leave</fullName>
            </value>
            <value>
                <fullName>PM leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApplicationItem__c/fields/Remark__c.field-meta.xml
<CustomField>
    <fullName>Remark__c</fullName>
    <label>Reason</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationItem__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sick leave</fullName>
            </value>
            <value>
                <fullName>Annual leave</fullName>
            </value>
            <value>
                <fullName>Personal leave</fullName>
            </value>
            <value>
                <fullName>Refresh Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement leave</fullName>
            </value>
            <value>
                <fullName>Marriage leave</fullName>
            </value>
            <value>
                <fullName>Maternity leave</fullName>
            </value>
            <value>
                <fullName>Military service leave</fullName>
            </value>
            <value>
                <fullName>Ordination leave</fullName>
            </value>
            <value>
                <fullName>Sterilization leave</fullName>
            </value>
            <value>
                <fullName>Training or knowledge leave</fullName>
            </value>
            <value>
                <fullName>Unpaid leave</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApplicationItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApplicationItem__c/fields/Term_From__c.field-meta.xml
<CustomField>
    <fullName>Term_From__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/createLeaveRecordQueueableTest.cls
@isTest
public class createLeaveRecordQueueableTest {

    @isTest
    static void testQueueableExecution() {
         User user = new User(
                    ProfileId = [SELECT Id FROM Profile WHERE Name = 'EngineerGroupMember'].Id,
                    LastName = 'last',
                    Email = 'testuser@terrasky.co.th',
                    Username = 'testuser@terrasky.co.th' + System.currentTimeMillis(),
                    CompanyName = 'TEST',
                    Title = 'title',
                    Alias = 'alias',
                    TimeZoneSidKey = 'Asia/Bangkok',
                    EmailEncodingKey = 'UTF-8',
                    LanguageLocaleKey = 'th',
                    LocaleSidKey = 'th'
                );
        insert user;
        // All day request
        ApplicationItem__c leaveRequestList = new ApplicationItem__c();
    
        leaveRequestList.Request_Type__c = 'Annual leave';
        leaveRequestList.Period_Leave__c = 'All day';
        leaveRequestList.Term_From__c = system.today();
        leaveRequestList.Remark__c = 'Test All day';
        leaveRequestList.Status__c = 'Pending';
        leaveRequestList.OwnerId = user.Id;
        insert leaveRequestList;
        // Enqueue the job
        Test.startTest();
            System.enqueueJob(new createLeaveRecordQueueable(leaveRequestList));
        Test.stopTest();

    }
}